### PR TITLE
Give memes fronk

### PR DESCRIPTION
**Pull request by FireArrow8790**
I need memes to bulli friends

### CODE REVIEW

**Comment by FrankTCA** [comment]
Why are you trying to merge `master` into `weird`?

To download the master branch, use
> git clone https://github.com/FrankTCA/DiscordMemes

To download weird branch, use
> git clone https://github.com/FrankTCA/DiscordMemes -b weird

**Comment by FrankTCA** [comment]
Please let me know if there was a genuine reason to make this pull request and elaborate more otherwise I'll close

**Comment by FrankTCA** [comment]
Also to update your existing repository just use
> git fetch origin
> git pull origin master

**Comment by FireArrow8790** [comment]
I have no idea how GitHub works, I just wanted to download the memes. Thanks!On Oct 26, 2022, at 12:50 PM, Frank ***@***.***> wrote:﻿
Please let me know if there was a genuine reason to make this pull request and elaborate more otherwise I'll close

**Pull request closed without merging**
